### ISSUE TITLE
For Scale Parameters, the Starting number of Cores is listed twice

### ISSUE THREAD

**Issue by andrew-solace** [KenBarr/Solace_testing_in_AWS#6]
For Scale Parameters, the Starting number of Cores is listed twice, this should have been the starting number of edge routers.  Note the comment is correct.

**Comment by KenBarr** [comment]
Fixed with commit:
https://github.com/SolaceLabs/solace-iot-reference-architecture/commit/fa8c2eb0021facb37d39fc67c5ed04ccb47043cf
